FullStack-DevTool/FSDT

.github/workflows/publish-packages.yml, package.json, packages/app/.npmignore, packages/app/.npmrc, packages/app/bin/start.js, packages/app/package.json, packages/app/src/front/views/ListView.tsx, packages/sdk/.npmignore, packages/sdk/.npmrc, packages/sdk/README.md, packages/sdk/package.json
- **What kind of change does this PR introduce?** 
Add github actions for publishing packages to npm.
=> :construction_worker: ci: add gh actions to publish packages

packages/app/package.json, packages/sdk/package.json
=> :memo: docs: add repository field

release-please-config.json
Add config files for release please
=> chore: add release please config files

.github/workflows/release-please.yml
=> chore: add release please workflow

release-please-config.json
=> chore: release-please separate pr by package

.husky/commit-msg, commitlint.config.js, package.json, yarn.lock
=> chore: add husky with commitlint

packages/app/src/front/index.html, packages/app/src/front/renderer.ts, packages/app/src/front/views/ListView.tsx, yarn.lock
New feature : Search bar
The search bar have no effects
Now, the search bar can filter text from all columns except DateTime
=> feat(app): implementing search bar

packages/app/package.json, packages/app/src/front/App.tsx, packages/app/src/front/components/GlobalStyles.tsx, packages/app/src/front/components/grid/LogCell.tsx, packages/app/src/front/views/ListView.tsx, packages/app/src/server/utils/getLogId.ts, packages/app/src/server/utils/sendMessage.ts, packages/app/src/tests/communication.spec.ts, packages/core/types/FsdtMessage.ts, packages/core/utils/messageFactory.ts, yarn.lock
Add json view for log cells.
The logs are displayed as string 
The logs are displayed as object, with the possibility to go through
=> feat(app): add json view

packages/app/package.json
=> fix(app): remove core package from dependency

.github/workflows/release-please.yml
=> fix: release please upgrade

.github/workflows/release-please.yml
=> fix: release please id

packages/app/src/front/components/grid/LogCell.tsx
Fixing application not showing correctly message content
If the message is a string ReactJson can't handdle it
ReactJson handle message only if it's an object
=> fix(app): removing ReactJson when string provided

packages/app/webpack.main.config.ts, packages/sdk/.gitignore, packages/sdk/package.json, packages/sdk/rollup.config.js, packages/sdk/tsconfig.json, yarn.lock
=> fix(sdk): add rollup config

packages/sdk/package.json
=> fix(sdk): add entry in field files

packages/app/package.json, packages/app/src/front/App.tsx, packages/app/src/front/components/grid/LogCell.tsx, packages/app/src/front/components/section/Header.tsx, packages/app/src/front/utils/globalStyle.ts, yarn.lock
=> fix(app): fonts

packages/app/webpack.rules.ts
=> fix(app): webpack rule for fonts

packages/app/src/front/components/ObjectView.tsx, packages/app/src/front/components/grid/LogCell.tsx, packages/app/src/front/views/ListView.tsx
The ReactJson component doesn't provide a good preview so I decided to implement a custom component for the preview mode. As soon as the user wants to interect with the object, ReactJson component takes care of the rest.
Moreover, I improved the search filter.
=> feat(app): create object view

packages/app/src/front/components/grid/LevelCell.tsx, packages/app/src/front/views/ListView.tsx
=> feat(app): column showing message level

README.md, packages/app/README.md, packages/sdk/README.md
Updated readme of sdk, app and monorepo
=> chore: update readme

CONTRIBUTING
=> chore: add contributing doc

README.md, packages/app/README.md, packages/sdk/README.md
=> chore: adding readme badges

README.md, packages/app/README.md, packages/sdk/README.md
=> fix: update contributing in readme
